backend:
  name: test-repo

collections:
  - name: blog-posts
    label: Blog Posts
    folder: content/blog
    fields:
      - { name: title, label: Title, widget: string }

  - name: news_items
    label: News Items
    folder: content/news
    fields:
      - { name: headline, label: Headline, widget: string }
